server/apps/tasks/urls.py
from django.urls import path
from apps.tasks.views import (
    create_view, update_view, delete_view, detail_view, list_view, playground_view
)

app_name = 'tasks'

urlpatterns = [
    path('create/', create_view, name='task-create'),
    path('edit/<int:pk>/', update_view, name='task-edit'),
    path('delete/<int:pk>/', delete_view, name='task-delete'),
    path('<int:pk>/', detail_view, name='task-detail'),
    path('', list_view, name='task-list'),
    path('playground/', playground_view, name='playground')
]

server/server/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', TemplateView.as_view(template_name='index.html')),
    path('accounts/', include('apps.accounts.urls', namespace='accounts')),
    path('tasks/', include('apps.tasks.urls', namespace='tasks')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

server/apps/tasks/models.py
from django.db import models
from django.utils import timezone

from apps.accounts.models import User

# Create your models here.


class Task(models.Model):
    title = models.CharField(max_length=100, unique=True)
    description = models.TextField(blank=True, null=True)
    due_date = models.DateTimeField(default=timezone.now)
    owner = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='tasks')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created']
        indexes = [
            models.Index(fields=['-created'])
        ]

    def __str__(self):
        return self.title

server/templates/components/messages_inner.html
{% for message in messages %}
<div data-turbo-temporary="true" data-controller="alert" data-alert-dismiss-after-value="1000" data-alert-remove-delay-value="0" class="{{ message.tags }}">
    <div class="w-full max-w-6xl mx-auto p-4 flex items-center justify-between">
        <span>{{ message|safe }}</span>
        <button data-action="alert#close" class="bg-transparent text-2xl font-semibold leading-none outline-none focus:outline-none">
            <span>x</span>
        </button>
    </div>
</div>
{% endfor %}

server/templates/components/spinner.html
<svg class="animate-spin -ml-1 mr-3 h-5 w-5 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
    <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
    <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
</svg>

server/templates/components/task_detail_inner.html
<div class="flex flex-col gap-2 border px-4 py-4">
  <header>
      <p>{{ task.owner }}</p>
      <h3 class="text-2xl">
          <a href="{% url 'tasks:task-detail' task.pk %}" data-turbo-frame="_top">{{ task.title }}</a>
      </h3>
  </header>
  {% if task.description %}
    <p class="text-gray-700">
        {{ task.description|truncatechars:60 }}
    </p>
  {% endif %}

  {% if request.user == task.owner %}
  <footer class="">
      {% if perms.tasks.change_task %}
      <button><a href="{% url 'tasks:task-edit' task.pk %}" class="btn-blue">Edit</a></button>
      {% endif %}
      
      {% if perms.tasks.delete_task %}
      <button><a href="{% url 'tasks:task-delete' task.pk %}" class="btn-red">Delete</a></button>
      {% endif %}
  </footer>
  {% endif %}
</div>