server/apps/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import (
    LoginView, LogoutView, PasswordResetView,
    PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView)

# from apps.accounts.forms import AuthenticationForm
from django.contrib.auth.forms import AuthenticationForm
from apps.accounts.views import SignupView, ProfileView, SettingsView, info_edit_view, EditPasswordView, email_edit_view

app_name = 'accounts'

urlpatterns = [
    path('signup/', SignupView.as_view(), name='signup'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('login/', LoginView.as_view(template_name='accounts/registration/login.html',
                                     form_class=AuthenticationForm), name='login'),

    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/settings/', SettingsView.as_view(), name='settings'),
    path('profile/settings/edit-personal-information',
         info_edit_view, name='edit_info'),
    path('profile/settings/edit-password/',
         EditPasswordView.as_view(), name='edit_password'),
    path('profile/settings/edit-email/',
         email_edit_view, name='edit_email'),

    path('password-reset/', PasswordResetView.as_view(
        template_name='accounts/registration/password_reset_form.html',
        email_template_name='accounts/registration/password_reset_email.html',
        success_url='/accounts/password-reset/done/'), name='password_reset'),

    path('password-reset/done/', PasswordResetDoneView.as_view(
        template_name='accounts/registration/password_reset_done.html'
    ), name='password_reset_done'),

    path('password-reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name='accounts/registration/password_reset_confirm.html',
        success_url='/accounts/password-reset/complete/'
    ), name='password_reset_confirm'),

    path('password-reset/complete/', PasswordResetCompleteView.as_view(
        template_name='accounts/registration/password_reset_complete.html'
    ), name='password_reset_complete')
]

server/apps/tasks/urls.py
from django.urls import path
from apps.tasks.views import (
    create_view, update_view, delete_view, detail_view, list_view, playground_view
)

app_name = 'tasks'

urlpatterns = [
    path('create/', create_view, name='task-create'),
    path('edit/<int:pk>/', update_view, name='task-edit'),
    path('delete/<int:pk>/', delete_view, name='task-delete'),
    path('<int:pk>/', detail_view, name='task-detail'),
    path('', list_view, name='task-list'),
    path('playground/', playground_view, name='playground')
]

server/server/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', TemplateView.as_view(template_name='index.html')),
    path('accounts/', include('apps.accounts.urls', namespace='accounts')),
    path('tasks/', include('apps.tasks.urls', namespace='tasks')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

server/templates/base.html
{% load webpack_loader static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    {% stylesheet_pack 'app' %}
    {% javascript_pack 'app' attrs='defer' %}
</head>
<body>
    <header class="w-full h-20 flex items-center border-b">
        <nav class="w-full max-w-6xl mx-auto flex items-center justify-between px-4">
            <div>
                <div>
                    <a href="/">Home</a>
                </div>
            </div>
            <div class="flex items-center gap-4">
                <div>
                    <a href="{% url 'tasks:playground' %}">Playground</a>
                </div>
                <div>
                    <a href="{% url 'tasks:task-list' %}">Tasks</a>
                </div>
                {% if request.user.is_authenticated %}
                <div>
                    <a href="{% url 'accounts:profile' %}">{{ request.user.username }}</a>
                </div>
                <div>
                    <a href="{% url 'accounts:logout' %}">Logout</a>
                </div>
                {% else %}
                <div>
                    <a href="{% url 'accounts:login' %}">Login</a>
                </div>
                <div>
                    <a href="{% url 'accounts:signup' %}">Register</a>
                </div>
                {% endif %}
            </div>
        </nav>
    </header>
    {% include 'messages.html' %}
    <main>
        <div class="w-full max-w-6xl mx-auto py-4 px-4">
            {% block content %}
            {% endblock %}
        </div>
    </main>
</body>
</html>

server/templates/index.html
{% extends 'base.html' %}

{% block content %}
<header class="mb-6 border-b pb-4">
    <h1 class="text-4xl mb-4">Turbo Frame Index</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Soluta quibusdam ratione nobis, accusantium quae assumenda id sit nihil tempora? Nesciunt est doloremque obcaecati eligendi ab iure rem? Doloribus, totam cum.</p>
</header>
<div class="mb-6">
    <turbo-frame id="task-create">
        <p><a href="{% url 'tasks:task-create' %}" class="btn-blue">Create a task</a></p>
    </turbo-frame>
</div>
<div>
    <turbo-frame id="task-list" src="{% url 'tasks:task-list' %}">
        <p>Loading...</p>
    </turbo-frame>
</div>
{% endblock %}

server/templates/messages.html
{% comment %}
MESSAGE_TAGS = {
    messages.INFO: 'bg-sky-500',
    messages.SUCCESS: 'bg-emerald-500',
    messages.WARNING: 'bg-amber-500',
    messages.ERROR: 'bg-red-500'
}
{% endcomment %}

<div class="w-full" id="messages">
    {% include 'components/messages_inner.html' %}
</div>