server/apps/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import (
    LoginView, LogoutView, PasswordResetView,
    PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView)

# from apps.accounts.forms import AuthenticationForm
from django.contrib.auth.forms import AuthenticationForm
from apps.accounts.views import SignupView, ProfileView, SettingsView, info_edit_view, EditPasswordView, email_edit_view

app_name = 'accounts'

urlpatterns = [
    path('signup/', SignupView.as_view(), name='signup'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('login/', LoginView.as_view(template_name='accounts/registration/login.html',
                                     form_class=AuthenticationForm), name='login'),

    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/settings/', SettingsView.as_view(), name='settings'),
    path('profile/settings/edit-personal-information',
         info_edit_view, name='edit_info'),
    path('profile/settings/edit-password/',
         EditPasswordView.as_view(), name='edit_password'),
    path('profile/settings/edit-email/',
         email_edit_view, name='edit_email'),

    path('password-reset/', PasswordResetView.as_view(
        template_name='accounts/registration/password_reset_form.html',
        email_template_name='accounts/registration/password_reset_email.html',
        success_url='/accounts/password-reset/done/'), name='password_reset'),

    path('password-reset/done/', PasswordResetDoneView.as_view(
        template_name='accounts/registration/password_reset_done.html'
    ), name='password_reset_done'),

    path('password-reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name='accounts/registration/password_reset_confirm.html',
        success_url='/accounts/password-reset/complete/'
    ), name='password_reset_confirm'),

    path('password-reset/complete/', PasswordResetCompleteView.as_view(
        template_name='accounts/registration/password_reset_complete.html'
    ), name='password_reset_complete')
]

server/server/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', TemplateView.as_view(template_name='index.html')),
    path('accounts/', include('apps.accounts.urls', namespace='accounts')),
    path('tasks/', include('apps.tasks.urls', namespace='tasks')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

server/apps/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.utils import timezone
# Create your models here.


class UserManager(BaseUserManager):
    def _create(self, username, email, password, **extra_fields):
        if not username:
            raise ValueError("The given username must be set")
        if not email:
            raise ValueError("The given email address must be set")

        user = self.model(email=self.normalize_email(email),
                          username=username, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, username, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create(username, email, password, **extra_fields)

    def create_superuser(self, username, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        return self._create(username, email, password, **extra_fields)


def get_profile_image_pathname(self, filename):
    print(filename)
    return f"profile/{self.pk}/{self.username}_{timezone.now()}_n.png"


class User(AbstractUser):
    username = models.CharField(max_length=50, unique=True)
    email = models.EmailField('Email address', unique=True)

    profile = models.ImageField(
        blank=True, upload_to=get_profile_image_pathname, default='default/44884218_345707102882519_2446069589734326272_n.jpg')
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    objects = UserManager()

    def __str__(self):
        return self.username

server/apps/accounts/forms.py
import logging
from django import forms
from django.contrib.auth import authenticate
from django.contrib.auth.forms import UserCreationForm as DjangoUserCreationForm, AuthenticationForm as DjangoAuthenticationForm
from django.core.mail import send_mail

from apps.accounts.models import User

logger = logging.getLogger(__name__)


class UserCreationForm(DjangoUserCreationForm):
    class Meta(DjangoUserCreationForm.Meta):
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    def send_mail(self):
        logger.info(
            f"Sending signup email for email={self.cleaned_data['email']}")

        message = "Welcome {}".format(self.cleaned_data['email'])

        send_mail("Welcome to BookTime", message, "site@booktime.domain",
                  [self.cleaned_data['email']], fail_silently=True)


# class AuthenticationForm(DjangoAuthenticationForm):
    # email = forms.EmailField()
    # password = forms.CharField(widget=forms.PasswordInput, strip=False)

    # def __init__(self, request=None, *args, **kwargs):
    #     self.request = request
    #     self.user = None
    #     super().__init__(*args, **kwargs)

    # def clean(self):
    #     email = self.cleaned_data.get('email')
    #     password = self.cleaned_data.get('password')

    #     if email is not None and password:
    #         self.user = authenticate(
    #             self.request, email=email, password=password)

    #         if self.user is None:
    #             logger.info(f"Authentication failed for email {email}")

    #             raise forms.ValidationError(
    #                 "Invalid email/password combination.")

    #         logger.info(f"Authentication successful for email {email}")

    #     return self.cleaned_data

    # def get_user(self):
    #     return self.user


class CustomeProfileInput(forms.widgets.FileInput):
    template_name = 'form/image_preview.html'


class PersonalInfoForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('profile', 'username', 'first_name', 'last_name')
        widgets = {
            'profile': CustomeProfileInput()
        }

    def clean(self):
        first_name = self.cleaned_data.get('first_name')
        last_name = self.cleaned_data.get('last_name')

        if not first_name and not last_name:
            raise forms.ValidationError(
                "Please provide your first name and your last name.")

        return self.cleaned_data

    def clean_username(self):
        username = self.cleaned_data.get('username')

        try:
            user = User.objects.exclude(pk=self.instance.pk).get(
                username__iexact=username)
        except User.DoesNotExist:
            return username

        raise forms.ValidationError(f"Username {user} already in user.")


class EmailEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('email',)

    def clean_email(self):
        email = self.cleaned_data.get('email')

        try:
            user = User.objects.exclude(pk=self.instance.pk).get(email=email)
        except User.DoesNotExist:
            return email

        raise forms.ValidationError(f"Email {user} already in use.")

server/apps/accounts/views.py
import logging
import http

from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from django.contrib.auth import login, authenticate
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.views.generic import FormView, TemplateView
from django.contrib.auth.views import PasswordChangeView
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required, permission_required

from apps.accounts.forms import UserCreationForm, PersonalInfoForm, EmailEditForm
from apps.accounts.models import User

logger = logging.getLogger(__name__)

# Create your views here.


class SignupView(FormView):
    template_name = 'accounts/registration/signup.html'
    form_class = UserCreationForm

    def get_success_url(self):
        redirect_to = self.request.GET.get('next', '/')
        return redirect_to

    def form_valid(self, form):
        response = super().form_valid(form)

        form.save()

        email = form.cleaned_data.get('email')
        raw_password = form.cleaned_data.get('password1')

        logger.info(f"New signup for email={email} through SignupView")

        user = authenticate(self.request, email=email, password=raw_password)
        login(self.request, user=user)

        form.send_mail()

        messages.success(self.request, "You signed up successfully.")

        return response


class ProfileView(LoginRequiredMixin, TemplateView):
    template_name = 'accounts/user/profile.html'
    # permission_required = 'accounts.view_user'


class SettingsView(LoginRequiredMixin, TemplateView):
    template_name = 'accounts/user/settings.html'


@login_required
@permission_required('accounts.change_user', raise_exception=True)
def info_edit_view(request):
    current_user = get_object_or_404(User, pk=request.user.pk)

    if request.method == 'POST':
        form = PersonalInfoForm(
            request.POST, request.FILES, instance=current_user)
        if form.is_valid():
            form.save()
            messages.success(
                request, "Personal information updated successfully")
            return redirect('accounts:edit_info')
        status = http.HTTPStatus.UNPROCESSABLE_ENTITY
    else:
        status = http.HTTPStatus.OK
        form = PersonalInfoForm(instance=current_user)

    return render(request, 'accounts/user/edit_personal_info.html', {
        'form': form
    }, status=status)


@login_required
@permission_required('accounts.change_user', raise_exception=True)
def email_edit_view(request):
    current_user = get_object_or_404(User, pk=request.user.pk)
    if request.method == 'POST':
        form = EmailEditForm(request.POST, instance=current_user)
        if form.is_valid():
            form.save()
            messages.success(request, "Email changed successfully")
            return redirect('accounts:edit_info')
        status = http.HTTPStatus.UNPROCESSABLE_ENTITY
    else:
        status = http.HTTPStatus.OK
        form = EmailEditForm(instance=current_user)

    return render(request, 'accounts/user/edit_email.html', {'form': form}, status=status)


class EditPasswordView(LoginRequiredMixin, PasswordChangeView):
    template_name = 'accounts/user/edit_password.html'
    success_url = reverse_lazy('accounts:settings')


class ProfileEditView(LoginRequiredMixin, TemplateView):
    template_name = 'accounts/user/settings.html'

server/templates/accounts/user/edit_email.html
{% extends 'accounts/user/settings.html' %}
{% load crispy_forms_tags %}

{% block content-form %}
<header class="mb-8">
    <h1 class="text-xl mb-2">Edit your email address</h1>
    <p class="text-gray-600">Lorem ipsum dolor sit amet consectetur adipisicing elit. At, cumque!</p>
</header>
<form action="{% url 'accounts:edit_email' %}" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="mt-8">
        <button type="submit" class="bg-black text-white px-4 py-2 rounded-md">Save</button>
    </div>
</form>
{% endblock %}

server/templates/accounts/user/edit_password.html
{% extends 'accounts/user/settings.html' %}
{% load crispy_forms_tags %}

{% block content-form %}
<header class="mb-8">
    <h1 class="text-xl mb-2">Personal Information</h1>
    <p class="text-gray-600">Lorem ipsum dolor sit amet consectetur adipisicing elit. At, cumque!</p>
</header>
<form action="{% url 'accounts:edit_password' %}" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="mt-8">
        <button type="submit" class="bg-black text-white px-4 py-2 rounded-md">Save</button>
    </div>
</form>
{% endblock %}

server/templates/accounts/user/edit_personal_info.html
{% extends 'accounts/user/settings.html' %}
{% load crispy_forms_tags %}

{% block content-form %}
<header class="mb-8">
    <h1 class="text-xl mb-2">Personal Information</h1>
    <p class="text-gray-600">Lorem ipsum dolor sit amet consectetur adipisicing elit. At, cumque!</p>
</header>
<form action="{% url 'accounts:edit_info' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="mt-8">
        <button type="submit" class="bg-black text-white px-4 py-2 rounded-md">Save</button>
    </div>
</form>
{% endblock %}

server/templates/accounts/user/settings.html
{% extends 'base.html' %}

{% block content %}
    <header class="mb-6 border-b pb-4">
        <p><a href="{% url 'accounts:profile' %}">Back To Profile</a></p>
        <h1 class="text-4xl mb-4">Settings</h1>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Soluta quibusdam ratione nobis, accusantium quae assumenda id sit nihil tempora? Nesciunt est doloremque obcaecati eligendi ab iure rem? Doloribus, totam cum.</p>
    </header>
    <div class="grid grid-cols-6 items-start">
        <aside class="col-start-1 col-end-3">
            <ul class="flex flex-col gap-2">
                <li><a href="{% url 'accounts:edit_info' %}">Personal Information</a></li>
                <li><a href="{% url 'accounts:edit_email' %}">Change your email address</a></li>
                <li><a href="{% url 'accounts:edit_password' %}">Change your password</a></li>
                <li><a href="#">Supports</a></li>
            </ul>
        </aside>
        <div class="col-start-3 col-end-[-1]">
            {% block content-form %}
            <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ullam maxime quaerat nostrum temporibus doloribus fuga. Incidunt quasi omnis, cupiditate quo, nobis aut itaque dignissimos hic sunt soluta, inventore explicabo? Labore modi veritatis maxime nostrum, totam consectetur repudiandae neque illo aliquam mollitia quos similique corrupti! Esse similique ab fuga voluptatem atque eveniet illum illo id, voluptate modi laudantium facere error perspiciatis quibusdam commodi, repudiandae accusantium dolorum. Iusto praesentium iste quidem, reprehenderit tempore non molestiae dolorum soluta, perferendis aspernatur ducimus quas temporibus rerum assumenda nisi magni veniam et nulla corrupti amet maxime aliquam quasi ratione molestias! Dignissimos veniam repellat hic asperiores ex.</p>
            {% endblock %}
        </div>
    </div>
{% endblock %}